enable-module-update = true
parallel-jobs = 1
remove-rv-integrations-checks = false

patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "arm64-v8a"

[AdGuard]
app-name = "AdGuard"
pkg-name = "com.adguard.android"
version = "auto"
github-dlurl = "https://github.com/AdguardTeam/AdguardForAndroid"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard/"
uptodown-dlurl = "https://adguard.en.uptodown.com/android"
module-prop-name = "adguard-morphe"

[Prime-Video]
app-name = "Prime-Video"
pkg-name = "com.amazon.avod.thirdpartyclient"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-prime-video.en.uptodown.com/android"
excluded-patches = "'Rename shared permissions'"
module-prop-name = "prime-video-morphe"
